Update LinuxKernelConf to 1.3, latest available.

diff --git a/scripts/kconfig/Makefile.kernel b/scripts/kconfig/Makefile.kernel
--- a/scripts/kconfig/Makefile.kernel
+++ b/scripts/kconfig/Makefile.kernel
@@ -23,33 +23,43 @@ clean-files	:= libkconfig.so lkc_defs.h qconf.moc .tmp_qtcheck \
 
 include $(TOPDIR)/Rules.make
 
-# QT needs some extra effort...
-ifndef QTDIR
-QTDIR		:= /usr/share/qt
-endif
-
-# Executable to generate the .moc file
-MOC=$(wildcard $(QTDIR)/bin/moc)
-
 # generated files seem to need this to find local include files
 HOSTCFLAGS_lex.zconf.o	:= -I$(src)
 HOSTCFLAGS_zconf.tab.o	:= -I$(src)
 
-HOSTLOADLIBES_qconf	:= -L$(QTDIR)/lib -Wl,-rpath,$(QTDIR)/lib -lqt -ldl
-HOSTCXXFLAGS_qconf.o	:= -I$(QTDIR)/include 
+HOSTLOADLIBES_qconf	= -L$(QTDIR)/lib -Wl,-rpath,$(QTDIR)/lib -l$(QTLIB) -ldl
+HOSTCXXFLAGS_qconf.o	= -I$(QTDIR)/include 
 
 $(obj)/conf.o $(obj)/mconf.o $(obj)/qconf.o: $(obj)/zconf.tab.h
 
 $(obj)/qconf.o: $(obj)/.tmp_qtcheck
 
+ifeq ($(MAKECMDGOALS),$(obj)/qconf)
+MOC = $(QTDIR)/bin/moc
+-include $(obj)/.tmp_qtcheck
+
+# QT needs some extra effort...
 $(obj)/.tmp_qtcheck:
-ifeq ($(MOC),)
-	@echo Unable to find the QT installation. Please make sure that the
-	@echo QT development package is correctly installed and the QTDIR
-	@echo environment variable is set to the correct location.
-	@false
-else
-	@touch $@
+	@set -e; for d in $$QTDIR /usr/share/qt /usr/lib/qt3; do \
+	  if [ -f $$d/include/qconfig.h ]; then DIR=$$d; break; fi; \
+	done; \
+	if [ -z "$$DIR" ]; then \
+	  echo "*"; \
+	  echo "* Unable to find the QT installation. Please make sure that the"; \
+	  echo "* QT development package is correctly installed and the QTDIR"; \
+	  echo "* environment variable is set to the correct location."; \
+	  echo "*"; \
+	  false; \
+	fi; \
+	LIB=qt; \
+	if [ -f $$DIR/lib/libqt-mt.so ]; then LIB=qt-mt; fi; \
+	echo "QTDIR=$$DIR" > $@; echo "QTLIB=$$LIB" >> $@; \
+	if [ ! -x $$DIR/bin/moc -a -x /usr/bin/moc ]; then \
+	  echo "*"; \
+	  echo "* Unable to find $$DIR/bin/moc, using /usr/bin/moc instead."; \
+	  echo "*"; \
+	  echo "MOC=/usr/bin/moc" >> $@; \
+	fi
 endif
 
 $(obj)/zconf.tab.o: $(obj)/lex.zconf.c
